[tools]
actionlint = "latest"
cspell = "latest"
"gem:rubocop" = "latest"
"gem:slim_lint" = "latest"
"gem:steep" = "latest"
node = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@github/copilot" = "latest"
"npm:ccusage" = "latest"
"npm:eslint" = "latest"
"npm:prettier" = "latest"
pinact = "latest"
ruby = "latest"
shellcheck = "latest"
shfmt = "latest"
stylua = "latest"
tombi = "latest"
yamlfmt = "latest"
